// App

export const SET_APP_DARK_THEME = 'SET_APP_DARK_THEME';
export const SET_APP_AUTO_SCROLL = 'SET_APP_AUTO_SCROLL';
export const SET_APP_TOGGLE_THEME = 'SET_APP_TOGGLE_THEME';


// Tracker

export const SET_TRACKER_TOPICS_LIST = 'SET_TRACKER_TOPICS_LIST';


// Conversation

export const SET_CONVERSATION_TOPIC = 'SET_CONVERSATION_TOPIC';
export const SET_CONVERSATION_VISITED = 'SET_CONVERSATION_VISITED';


// Favourites

export const SET_FAVOURITES_TOPICS = 'SET_FAVOURITES_TOPICS';
export const SET_FAVOURITES_COMMENTS = 'SET_FAVOURITES_COMMENTS';


// Forums

export const SET_FORUMS_LIST = 'SET_FORUMS_LIST';


// Last topics

export const SET_LAST_TOPICS_FORUM = 'SET_LAST_TOPICS_FORUM';
export const SET_LAST_TOPICS_LIST = 'SET_LAST_TOPICS_LIST';
