// App

export const SET_APP_DARK_THEME = 'SET_APP_DARK_THEME';


// Tracker

export const SET_TRACKER_TOPICS_LIST = 'SET_TRACKER_TOPICS_LIST';


// Conversation

export const SET_CONVERSATION_COMMENTS_LIST = 'SET_CONVERSATION_COMMENTS_LIST';
export const SET_CONVERSATION_TOPIC = 'SET_CONVERSATION_TOPIC';
export const SET_CONVERSATION_COMMENTS_PAGES = 'SET_CONVERSATION_COMMENTS_PAGES';
export const SET_CONVERSATION_COMMENTS_CURRENT_PAGE = 'SET_CONVERSATION_COMMENTS_CURRENT_PAGE';


// Favourites

export const SET_FAVOURITES_TOPICS = 'SET_FAVOURITES_TOPICS';
export const SET_FAVOURITES_COMMENTS = 'SET_FAVOURITES_COMMENTS';


// Forums

export const SET_FORUMS_LIST = 'SET_FORUMS_LIST';


// Last topics

export const SET_LAST_TOPICS_FORUM = 'SET_LAST_TOPICS_FORUM';
export const SET_LAST_TOPICS_LIST = 'SET_LAST_TOPICS_LIST';
